### ISSUE TITLE
./install.sh issues on python-scripts branch

### ISSUE THREAD

**Issue by brainstorm** [umccr/aws_parallel_cluster#4]
I'm taking a look at the following issue, @alexiswl:

```
% chmod +x install.sh && ./install.sh
+ PCLUSTER_CONDA_ENV_NAME=pcluster
++ get_this_path
++ : '
  Mac users use greadlink over readlink
  Return the directory of where this install.sh file is located
  '
++ local this_dir
++ [[ darwin19 == \d\a\r\w\i\n* ]]
++ readlink_program=greadlink
++++ greadlink -f ./install.sh
+++ dirname /Users/rvalls/dev/umccr/aws_parallel_cluster/install.sh
++ this_dir=/Users/rvalls/dev/umccr/aws_parallel_cluster
++ echo /Users/rvalls/dev/umccr/aws_parallel_cluster
+ CONDA_ENV_FILE=/Users/rvalls/dev/umccr/aws_parallel_cluster/conf/pcluster-env.yaml
+ REQUIRED_CONDA_VERSION=4.9.0
+ echo_stderr 'Checking conda and jq are installed'
+ echo 'Checking conda and jq are installed'
Checking conda and jq are installed
+ has_conda
+ conda --version
+ has_jq
+ jq --version
+ check_conda_version
+ : '
  Make sure at the latest conda version
  '
++ get_conda_version
++ local version
+++ conda --version
+++ cut '-d ' -f2
++ version=4.9.2
++ echo 4.9.2
+ _verlte 4.9.0 4.9.2
++ echo -e '4.9.0\n4.9.2'
++ sort -V
++ head -n1
+ '[' 4.9.0 = 4.9.0 ']'
+ has_conda_env
+ : '
  Check if a conda environment exists
  '
+ local conda_envs
+ local conda_env_path
++ conda env list --json --quiet
++ jq --raw-output '.envs[]'
+ conda_envs='/Users/rvalls/.miniconda3
/usr/local/Caskroom/miniconda/base
/usr/local/Caskroom/miniconda/base/envs/analytics
/usr/local/Caskroom/miniconda/base/envs/cdk
/usr/local/Caskroom/miniconda/base/envs/data-portal
/usr/local/Caskroom/miniconda/base/envs/parallel_cluster'
+ for conda_env_path in '${conda_envs}'
++ basename /Users/rvalls/.miniconda3
+ [[ .miniconda3 == \p\c\l\u\s\t\e\r ]]
+ for conda_env_path in '${conda_envs}'
++ basename /usr/local/Caskroom/miniconda/base
+ [[ base == \p\c\l\u\s\t\e\r ]]
+ for conda_env_path in '${conda_envs}'
++ basename /usr/local/Caskroom/miniconda/base/envs/analytics
+ [[ analytics == \p\c\l\u\s\t\e\r ]]
+ for conda_env_path in '${conda_envs}'
++ basename /usr/local/Caskroom/miniconda/base/envs/cdk
+ [[ cdk == \p\c\l\u\s\t\e\r ]]
+ for conda_env_path in '${conda_envs}'
++ basename /usr/local/Caskroom/miniconda/base/envs/data-portal
+ [[ data-portal == \p\c\l\u\s\t\e\r ]]
+ for conda_env_path in '${conda_envs}'
++ basename /usr/local/Caskroom/miniconda/base/envs/parallel_cluster
+ [[ parallel_cluster == \p\c\l\u\s\t\e\r ]]
+ return 1
+ echo_stderr 'pcluster conda env does not exist. Creating'
+ echo 'pcluster conda env does not exist. Creating'
pcluster conda env does not exist. Creating
+ conda env create --quiet --name pcluster --file /Users/rvalls/dev/umccr/aws_parallel_cluster/conf/pcluster-env.yaml
Collecting package metadata (repodata.json): ...working... failed
WARNING conda.exceptions:print_unexpected_error_report(1213): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 118, in execute
    result[installer_type] = installer.install(prefix, pkg_specs, args, env)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda_env/installers/conda.py", line 32, in install
    prune=getattr(args, 'prune', False), update_modifier=UpdateModifier.FREEZE_INSTALLED)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/core/solve.py", line 262, in solve_final_state
    ssc = self._collect_all_metadata(ssc)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/core/solve.py", line 397, in _collect_all_metadata
    _supplement_index_with_system(virtual_pkg_index)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/core/index.py", line 158, in _supplement_index_with_system
    cuda_version = context.cuda_version
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/common/decorators.py", line 20, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/base/context.py", line 818, in cuda_version
    return cuda_detect()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
    import ctypes
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/usr/local/Caskroom/miniconda/base/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /usr/local/Caskroom/miniconda/base/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/exceptions.py", line 1211, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/cli/main_info.py", line 238, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 118, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda_env/installers/conda.py", line 32, in install
        prune=getattr(args, 'prune', False), update_modifier=UpdateModifier.FREEZE_INSTALLED)
      File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/core/solve.py", line 397, in _collect_all_metadata
        _supplement_index_with_system(virtual_pkg_index)
      File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/core/index.py", line 158, in _supplement_index_with_system
        cuda_version = context.cuda_version
      File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
        cache[inner_attname] = func(self)
      File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/common/decorators.py", line 20, in wrapper
        return func(*args, **kwargs)
      File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/base/context.py", line 818, in cuda_version
        return cuda_detect()
      File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
        import ctypes
      File "/usr/local/Caskroom/miniconda/base/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/usr/local/Caskroom/miniconda/base/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
      Referenced from: /usr/local/Caskroom/miniconda/base/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
      Reason: image not found

`$ /usr/local/Caskroom/miniconda/base/bin/conda-env create --quiet --name pcluster --file /Users/rvalls/dev/umccr/aws_parallel_cluster/conf/pcluster-env.yaml`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

Upload successful.
```

**Comment by brainstorm** [comment]
I'm not sure that creating venvs for the (power) user is the cleanest. I'd begin that `./install.sh` script under the assumption that the user has already created such an env either with conda or with regular python3 venvs?... just an opinion, I see what you were trying to do here w.r.t UX, simplifying the process for the user 👍

**Comment by alexiswl** [comment]
I can't reproduce this from my end

Do you have the PYTHONPATH variable set? I wonder if that's causing the problem.  That's what I've picked up from here:
https://github.com/conda/conda/issues/9356

The benefits of having the conda env is that it means the env is updated on a new release with the same `install.sh` command.  

If it is a PYTHONPATH issue, we can update the `install.sh` to unset the PYTHONPATH and the `activate.d` and `deactivate.d` to control its value as users enter / exit the conda environment.

**Comment by brainstorm** [comment]
Nope, `PYTHONPATH` is empty :-S

I tried from `base` and from an already existing conda env, same effect.

**Comment by alexiswl** [comment]
This one could also be the problem: https://github.com/conda/conda/issues/9038

I do get your point though about creating user conda environments not being part of the standard installation process for a script. Maybe this could be mitigated with a prompt regarding an installation instead?

**Comment by brainstorm** [comment]
Yes, the upgrade from conda 4.8.3 to 4.9.0 broke all my conda envs with the error messages above :-S

```
+ '[' 4.9.0 = 4.8.3 ']'
+ echo_stderr 'Your conda version is too old'
+ echo 'Your conda version is too old'
```

Is it really needed to upgrade to that version?

I'd advocate to remove conda/venv mangling from `install.sh` and/or make it optional given today's venvs-nuked experience ;)

**Comment by alexiswl** [comment]
> Is it really needed to upgrade to that version?
I thought I remembered having an issue when being at an older version for running one of the env commands.  

The fact that `conda env -n base update conda` has broken envs on MacOS is a disaster. Do you think it's the upgrade itself, i.e a re-install of 4.9.0 will resolve the issue?

**Comment by alexiswl** [comment]
> make it optional

The only issue is that the installation is based out of having a conda env to know where the binaries and configuration files are saved to (via a `CONDA_PREFIX` env var). It also makes the GitHub actions workflows easy to launch.
