### ISSUE TITLE
sinteractive ssm error needs attention

### ISSUE THREAD

**Issue by alexiswl** [umccr/aws_parallel_cluster#6]
## Launch cluster
```
$ start_cluster.py --cluster-name two-ten-one-test --no-rollback
Received exit code "1" for command "pcluster" "create" "--config" "/tmp/tmp42ef9_jb" "--cluster-template" "two-ten-one-test" "--norollback" "two-ten-one-test"
Stdout was:
"Beginning cluster creation for cluster: two-ten-one-test
Creating stack named: parallelcluster-two-ten-one-test
Status: parallelcluster-two-ten-one-test - CREATE_FAILED
Cluster creation failed.  Failed events:
  - AWS::CloudFormation::Stack parallelcluster-two-ten-one-test The following resource(s) failed to create: [MasterServerSubstack].
  - AWS::CloudFormation::Stack MasterServerSubstack Embedded stack arn:aws:cloudformation:ap-southeast-2:843407916570:stack/parallelcluster-two-ten-one-test-MasterServerSubstack-ZJ3JDVSFEAFV/1cbd6600-6040-11eb-85e5-0a47e77f90bc was not successfully created: The following resource(s) failed to create: [MasterServer].
    - AWS::CloudFormation::Stack parallelcluster-two-ten-one-test-MasterServerSubstack-ZJ3JDVSFEAFV The following resource(s) failed to create: [MasterServer].
    - AWS::EC2::Instance MasterServer Received FAILURE signal with UniqueId i-0c0a05a0348f17bbd"
Stderr was:
""
Failed to create the stack successfully
Traceback (most recent call last):
  File "/home/alexiswl/anaconda3/envs/pcluster/bin/start_cluster.py", line 281, in <module>
    main()
  File "/home/alexiswl/anaconda3/envs/pcluster/bin/start_cluster.py", line 273, in main
    run_pcluster_create(pcluster_create_command)
  File "/home/alexiswl/anaconda3/envs/pcluster/bin/start_cluster.py", line 222, in run_pcluster_create
    raise PClusterCreateError
umccr_utils.errors.PClusterCreateError
```

## Log into master instance
```
$ ssm  i-0c0a05a0348f17bbd
```

## Show cfn-init-cmd.log
```
$ cat /var/log/cfn-init-cmd.log
2021-01-27 12:46:47,279 P18656 [INFO] ============================================================
2021-01-27 12:46:47,279 P18656 [INFO] Command runpostinstall
2021-01-27 12:46:54,637 P18656 [INFO] -----------------------Command Output-----------------------
2021-01-27 12:46:54,637 P18656 [INFO]   Enabling --mem parameter on slurm
2021-01-27 12:46:54,637 P18656 [INFO]   Adding sinteractive command to /usr/local/bin
2021-01-27 12:46:54,637 P18656 [INFO]   fatal error: An error occurred (404) when calling the HeadObject operation: Key "parallel-cluster/pre-v2.10.1-1.0.0/slurm/scripts/sinteractive.sh" does not exist
2021-01-27 12:46:54,637 P18656 [INFO]   parallelcluster: fetch_and_run - Failed to run postinstall, s3://umccr-research-dev/parallel-cluster/pre-v2.10.1-1.0.0/bootstrap/post_install.sh failed with non 0 return code: 1
2021-01-27 12:46:54,638 P18656 [INFO] ------------------------------------------------------------
2021-01-27 12:46:54,638 P18656 [ERROR] Exited with error code 1
```

**Comment by alexiswl** [comment]
Resolved
